extends: standard
rules:
  prefer-const: error
  no-var: error
  no-multi-spaces: off
  array-bracket-spacing:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  operator-linebreak:
    - error
    - before
